version: "3.9"

services:
  crowbond.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    volumes:
      - ${APPDATA:-$HOME/.microsoft}/usersecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA:-$HOME/.aspnet}/https:/home/app/.aspnet/https:ro
