// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Crowbond.Modules.OMS.Infrastructure.Database.Migrations;

/// <inheritdoc />
public partial class Rename_AuditDate_Columns : Migration
{
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.RenameColumn(
            name: "last_modified_date",
            schema: "oms",
            table: "purchase_order_headers",
            newName: "last_modified_on_utc");

        migrationBuilder.RenameColumn(
            name: "create_date",
            schema: "oms",
            table: "purchase_order_headers",
            newName: "created_on_utc");

        migrationBuilder.RenameColumn(
            name: "create_by",
            schema: "oms",
            table: "purchase_order_headers",
            newName: "created_by");
    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.RenameColumn(
            name: "last_modified_on_utc",
            schema: "oms",
            table: "purchase_order_headers",
            newName: "last_modified_date");

        migrationBuilder.RenameColumn(
            name: "created_on_utc",
            schema: "oms",
            table: "purchase_order_headers",
            newName: "create_date");

        migrationBuilder.RenameColumn(
            name: "created_by",
            schema: "oms",
            table: "purchase_order_headers",
            newName: "create_by");
    }
}
