// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Crowbond.Modules.OMS.Infrastructure.Database.Migrations;

/// <inheritdoc />
public partial class Orders_Add_CustomerAccountNumber : Migration
{
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropColumn(
            name: "order_number",
            schema: "oms",
            table: "order_headers");

        migrationBuilder.DropColumn(
            name: "purchase_order_number",
            schema: "oms",
            table: "order_headers");

        migrationBuilder.AddColumn<Guid>(
            name: "created_by",
            schema: "oms",
            table: "order_headers",
            type: "uuid",
            nullable: false,
            defaultValue: Guid.Empty);

        migrationBuilder.AddColumn<DateTime>(
            name: "created_on_utc",
            schema: "oms",
            table: "order_headers",
            type: "timestamp with time zone",
            nullable: false,
            defaultValue: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

        migrationBuilder.AddColumn<string>(
            name: "customer_account_number",
            schema: "oms",
            table: "order_headers",
            type: "character varying(20)",
            maxLength: 20,
            nullable: false,
            defaultValue: "");

        migrationBuilder.AddColumn<Guid>(
            name: "last_modified_by",
            schema: "oms",
            table: "order_headers",
            type: "uuid",
            nullable: true);

        migrationBuilder.AddColumn<DateTime>(
            name: "last_modified_on_utc",
            schema: "oms",
            table: "order_headers",
            type: "timestamp with time zone",
            nullable: true);

        migrationBuilder.AddColumn<string>(
            name: "order_no",
            schema: "oms",
            table: "order_headers",
            type: "character varying(20)",
            maxLength: 20,
            nullable: false,
            defaultValue: "");

        migrationBuilder.AddColumn<string>(
            name: "purchase_order_no",
            schema: "oms",
            table: "order_headers",
            type: "character varying(20)",
            maxLength: 20,
            nullable: true);
    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropColumn(
            name: "created_by",
            schema: "oms",
            table: "order_headers");

        migrationBuilder.DropColumn(
            name: "created_on_utc",
            schema: "oms",
            table: "order_headers");

        migrationBuilder.DropColumn(
            name: "customer_account_number",
            schema: "oms",
            table: "order_headers");

        migrationBuilder.DropColumn(
            name: "last_modified_by",
            schema: "oms",
            table: "order_headers");

        migrationBuilder.DropColumn(
            name: "last_modified_on_utc",
            schema: "oms",
            table: "order_headers");

        migrationBuilder.DropColumn(
            name: "order_no",
            schema: "oms",
            table: "order_headers");

        migrationBuilder.DropColumn(
            name: "purchase_order_no",
            schema: "oms",
            table: "order_headers");

        migrationBuilder.AddColumn<string>(
            name: "order_number",
            schema: "oms",
            table: "order_headers",
            type: "character varying(100)",
            maxLength: 100,
            nullable: false,
            defaultValue: "");

        migrationBuilder.AddColumn<string>(
            name: "purchase_order_number",
            schema: "oms",
            table: "order_headers",
            type: "character varying(100)",
            maxLength: 100,
            nullable: true);
    }
}
