// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Crowbond.Modules.OMS.Infrastructure.Database.Migrations;

/// <inheritdoc />
public partial class Add_Product_Categories_Id_To_Lines : Migration
{
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.AddColumn<Guid>(
            name: "brand_id",
            schema: "oms",
            table: "purchase_order_lines",
            type: "uuid",
            nullable: false,
            defaultValue: Guid.Empty);

        migrationBuilder.AddColumn<Guid>(
            name: "category_id",
            schema: "oms",
            table: "purchase_order_lines",
            type: "uuid",
            nullable: false,
            defaultValue: Guid.Empty);

        migrationBuilder.AddColumn<Guid>(
            name: "product_group_id",
            schema: "oms",
            table: "purchase_order_lines",
            type: "uuid",
            nullable: false,
            defaultValue: Guid.Empty);

        migrationBuilder.AddColumn<Guid>(
            name: "brand_id",
            schema: "oms",
            table: "order_lines",
            type: "uuid",
            nullable: false,
            defaultValue: Guid.Empty);

        migrationBuilder.AddColumn<Guid>(
            name: "category_id",
            schema: "oms",
            table: "order_lines",
            type: "uuid",
            nullable: false,
            defaultValue: Guid.Empty);

        migrationBuilder.AddColumn<Guid>(
            name: "product_group_id",
            schema: "oms",
            table: "order_lines",
            type: "uuid",
            nullable: false,
            defaultValue: Guid.Empty);
    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropColumn(
            name: "brand_id",
            schema: "oms",
            table: "purchase_order_lines");

        migrationBuilder.DropColumn(
            name: "category_id",
            schema: "oms",
            table: "purchase_order_lines");

        migrationBuilder.DropColumn(
            name: "product_group_id",
            schema: "oms",
            table: "purchase_order_lines");

        migrationBuilder.DropColumn(
            name: "brand_id",
            schema: "oms",
            table: "order_lines");

        migrationBuilder.DropColumn(
            name: "category_id",
            schema: "oms",
            table: "order_lines");

        migrationBuilder.DropColumn(
            name: "product_group_id",
            schema: "oms",
            table: "order_lines");
    }
}
