// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Crowbond.Modules.OMS.Infrastructure.Database.Migrations;

/// <inheritdoc />
public partial class Alter_OrderDelivery_Table : Migration
{
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropTable(
            name: "delivery_images",
            schema: "oms");

        migrationBuilder.DropTable(
            name: "deliveries",
            schema: "oms");

        migrationBuilder.DropTable(
            name: "route_trip_log_datails",
            schema: "oms");

        migrationBuilder.CreateTable(
            name: "order_deliveries",
            schema: "oms",
            columns: table => new
            {
                id = table.Column<Guid>(type: "uuid", nullable: false),
                route_trip_log_id = table.Column<Guid>(type: "uuid", nullable: false),
                order_header_id = table.Column<Guid>(type: "uuid", nullable: false),
                status = table.Column<int>(type: "integer", nullable: false),
                date_time = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                comments = table.Column<string>(type: "character varying(255)", maxLength: 255, nullable: true)
            },
            constraints: table =>
            {
                table.PrimaryKey("pk_order_deliveries", x => x.id);
                table.ForeignKey(
                    name: "fk_order_deliveries_order_headers_order_header_id",
                    column: x => x.order_header_id,
                    principalSchema: "oms",
                    principalTable: "order_headers",
                    principalColumn: "id",
                    onDelete: ReferentialAction.Cascade);
                table.ForeignKey(
                    name: "fk_order_deliveries_route_trip_logs_route_trip_log_id",
                    column: x => x.route_trip_log_id,
                    principalSchema: "oms",
                    principalTable: "route_trip_logs",
                    principalColumn: "id");
            });

        migrationBuilder.CreateTable(
            name: "order_delivery_images",
            schema: "oms",
            columns: table => new
            {
                id = table.Column<Guid>(type: "uuid", nullable: false),
                order_delivery_id = table.Column<Guid>(type: "uuid", nullable: false),
                image_name = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false)
            },
            constraints: table =>
            {
                table.PrimaryKey("pk_order_delivery_images", x => x.id);
                table.ForeignKey(
                    name: "fk_order_delivery_images_order_deliveries_order_delivery_id",
                    column: x => x.order_delivery_id,
                    principalSchema: "oms",
                    principalTable: "order_deliveries",
                    principalColumn: "id",
                    onDelete: ReferentialAction.Cascade);
            });

        migrationBuilder.CreateIndex(
            name: "ix_order_deliveries_order_header_id",
            schema: "oms",
            table: "order_deliveries",
            column: "order_header_id",
            unique: true);

        migrationBuilder.CreateIndex(
            name: "ix_order_deliveries_route_trip_log_id",
            schema: "oms",
            table: "order_deliveries",
            column: "route_trip_log_id");

        migrationBuilder.CreateIndex(
            name: "ix_order_delivery_images_order_delivery_id",
            schema: "oms",
            table: "order_delivery_images",
            column: "order_delivery_id");
    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropTable(
            name: "order_delivery_images",
            schema: "oms");

        migrationBuilder.DropTable(
            name: "order_deliveries",
            schema: "oms");

        migrationBuilder.CreateTable(
            name: "route_trip_log_datails",
            schema: "oms",
            columns: table => new
            {
                id = table.Column<Guid>(type: "uuid", nullable: false),
                date_time = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                order_header_id = table.Column<Guid>(type: "uuid", nullable: false),
                route_trip_log_id = table.Column<Guid>(type: "uuid", nullable: false),
                status = table.Column<int>(type: "integer", nullable: false)
            },
            constraints: table =>
            {
                table.PrimaryKey("pk_route_trip_log_datails", x => x.id);
                table.ForeignKey(
                    name: "fk_route_trip_log_datails_order_headers_order_header_id",
                    column: x => x.order_header_id,
                    principalSchema: "oms",
                    principalTable: "order_headers",
                    principalColumn: "id");
                table.ForeignKey(
                    name: "fk_route_trip_log_datails_route_trip_logs_route_trip_log_id",
                    column: x => x.route_trip_log_id,
                    principalSchema: "oms",
                    principalTable: "route_trip_logs",
                    principalColumn: "id");
            });

        migrationBuilder.CreateTable(
            name: "deliveries",
            schema: "oms",
            columns: table => new
            {
                id = table.Column<Guid>(type: "uuid", nullable: false),
                comments = table.Column<string>(type: "character varying(255)", maxLength: 255, nullable: true),
                date_time = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                route_trip_log_detail_id = table.Column<Guid>(type: "uuid", nullable: false)
            },
            constraints: table =>
            {
                table.PrimaryKey("pk_deliveries", x => x.id);
                table.ForeignKey(
                    name: "fk_deliveries_route_trip_log_datails_route_trip_log_detail_id",
                    column: x => x.route_trip_log_detail_id,
                    principalSchema: "oms",
                    principalTable: "route_trip_log_datails",
                    principalColumn: "id");
            });

        migrationBuilder.CreateTable(
            name: "delivery_images",
            schema: "oms",
            columns: table => new
            {
                id = table.Column<Guid>(type: "uuid", nullable: false),
                delivery_id = table.Column<Guid>(type: "uuid", nullable: false),
                image_id = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false)
            },
            constraints: table =>
            {
                table.PrimaryKey("pk_delivery_images", x => x.id);
                table.ForeignKey(
                    name: "fk_delivery_images_deliveries_delivery_id",
                    column: x => x.delivery_id,
                    principalSchema: "oms",
                    principalTable: "deliveries",
                    principalColumn: "id",
                    onDelete: ReferentialAction.Cascade);
            });

        migrationBuilder.CreateIndex(
            name: "ix_deliveries_route_trip_log_detail_id",
            schema: "oms",
            table: "deliveries",
            column: "route_trip_log_detail_id");

        migrationBuilder.CreateIndex(
            name: "ix_delivery_images_delivery_id",
            schema: "oms",
            table: "delivery_images",
            column: "delivery_id");

        migrationBuilder.CreateIndex(
            name: "ix_route_trip_log_datails_order_header_id",
            schema: "oms",
            table: "route_trip_log_datails",
            column: "order_header_id",
            unique: true);

        migrationBuilder.CreateIndex(
            name: "ix_route_trip_log_datails_route_trip_log_id",
            schema: "oms",
            table: "route_trip_log_datails",
            column: "route_trip_log_id");
    }
}
