// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Crowbond.Modules.CRM.Infrastructure.Database.Migrations;

/// <inheritdoc />
public partial class create_sequence_table : Migration
{
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.AlterColumn<string>(
            name: "account_number",
            schema: "crm",
            table: "suppliers",
            type: "text",
            nullable: false,
            oldClrType: typeof(int),
            oldType: "integer");

        migrationBuilder.AlterColumn<string>(
            name: "account_number",
            schema: "crm",
            table: "customers",
            type: "text",
            nullable: false,
            oldClrType: typeof(int),
            oldType: "integer");

        migrationBuilder.AddColumn<string>(
            name: "customer_contact",
            schema: "crm",
            table: "customers",
            type: "text",
            nullable: false,
            defaultValue: "");

        migrationBuilder.AddColumn<string>(
            name: "customer_email",
            schema: "crm",
            table: "customers",
            type: "text",
            nullable: false,
            defaultValue: "");

        migrationBuilder.AddColumn<string>(
            name: "customer_phone",
            schema: "crm",
            table: "customers",
            type: "text",
            nullable: false,
            defaultValue: "");

        migrationBuilder.CreateTable(
            name: "sequences",
            schema: "crm",
            columns: table => new
            {
                id = table.Column<Guid>(type: "uuid", nullable: false),
                context = table.Column<int>(type: "integer", nullable: false),
                last_number = table.Column<int>(type: "integer", nullable: false)
            },
            constraints: table =>
            {
                table.PrimaryKey("pk_sequences", x => x.id);
            });
    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropTable(
            name: "sequences",
            schema: "crm");

        migrationBuilder.DropColumn(
            name: "customer_contact",
            schema: "crm",
            table: "customers");

        migrationBuilder.DropColumn(
            name: "customer_email",
            schema: "crm",
            table: "customers");

        migrationBuilder.DropColumn(
            name: "customer_phone",
            schema: "crm",
            table: "customers");

        migrationBuilder.AlterColumn<int>(
            name: "account_number",
            schema: "crm",
            table: "suppliers",
            type: "integer",
            nullable: false,
            oldClrType: typeof(string),
            oldType: "text");

        migrationBuilder.AlterColumn<int>(
            name: "account_number",
            schema: "crm",
            table: "customers",
            type: "integer",
            nullable: false,
            oldClrType: typeof(string),
            oldType: "text");
    }
}
