// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Crowbond.Modules.CRM.Infrastructure.Database.Migrations;

/// <inheritdoc />
public partial class Add_DeletedBy : Migration
{
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.RenameColumn(
            name: "last_modified_date",
            schema: "crm",
            table: "customer_contacts",
            newName: "last_modified_on_utc");

        migrationBuilder.RenameColumn(
            name: "create_date",
            schema: "crm",
            table: "customer_contacts",
            newName: "created_on_utc");

        migrationBuilder.RenameColumn(
            name: "create_by",
            schema: "crm",
            table: "customer_contacts",
            newName: "created_by");

        migrationBuilder.AddColumn<Guid>(
            name: "deleted_by",
            schema: "crm",
            table: "supplier_products",
            type: "uuid",
            nullable: false,
            defaultValue: Guid.Empty);

        migrationBuilder.AddColumn<Guid>(
            name: "deleted_by",
            schema: "crm",
            table: "supplier_contacts",
            type: "uuid",
            nullable: false,
            defaultValue: Guid.Empty);

        migrationBuilder.AddColumn<DateTime>(
            name: "deleted_on_utc",
            schema: "crm",
            table: "supplier_contacts",
            type: "timestamp with time zone",
            nullable: true);

        migrationBuilder.AddColumn<bool>(
            name: "is_deleted",
            schema: "crm",
            table: "supplier_contacts",
            type: "boolean",
            nullable: false,
            defaultValue: false);

        migrationBuilder.AddColumn<Guid>(
            name: "deleted_by",
            schema: "crm",
            table: "customer_outlets",
            type: "uuid",
            nullable: false,
            defaultValue: Guid.Empty);

        migrationBuilder.AddColumn<Guid>(
            name: "deleted_by",
            schema: "crm",
            table: "customer_contacts",
            type: "uuid",
            nullable: false,
            defaultValue: Guid.Empty);

        migrationBuilder.AddColumn<DateTime>(
            name: "deleted_on_utc",
            schema: "crm",
            table: "customer_contacts",
            type: "timestamp with time zone",
            nullable: true);

        migrationBuilder.AddColumn<bool>(
            name: "is_deleted",
            schema: "crm",
            table: "customer_contacts",
            type: "boolean",
            nullable: false,
            defaultValue: false);
    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropColumn(
            name: "deleted_by",
            schema: "crm",
            table: "supplier_products");

        migrationBuilder.DropColumn(
            name: "deleted_by",
            schema: "crm",
            table: "supplier_contacts");

        migrationBuilder.DropColumn(
            name: "deleted_on_utc",
            schema: "crm",
            table: "supplier_contacts");

        migrationBuilder.DropColumn(
            name: "is_deleted",
            schema: "crm",
            table: "supplier_contacts");

        migrationBuilder.DropColumn(
            name: "deleted_by",
            schema: "crm",
            table: "customer_outlets");

        migrationBuilder.DropColumn(
            name: "deleted_by",
            schema: "crm",
            table: "customer_contacts");

        migrationBuilder.DropColumn(
            name: "deleted_on_utc",
            schema: "crm",
            table: "customer_contacts");

        migrationBuilder.DropColumn(
            name: "is_deleted",
            schema: "crm",
            table: "customer_contacts");

        migrationBuilder.RenameColumn(
            name: "last_modified_on_utc",
            schema: "crm",
            table: "customer_contacts",
            newName: "last_modified_date");

        migrationBuilder.RenameColumn(
            name: "created_by",
            schema: "crm",
            table: "customer_contacts",
            newName: "create_by");

        migrationBuilder.RenameColumn(
            name: "created_on_utc",
            schema: "crm",
            table: "customer_contacts",
            newName: "create_date");
    }
}
