// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Crowbond.Modules.CRM.Infrastructure.Database.Migrations;

/// <inheritdoc />
public partial class Add_Customer_Product_Price_History : Migration
{
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropTable(
            name: "customer_product_prices",
            schema: "crm");

        migrationBuilder.AddColumn<string>(
            name: "comments",
            schema: "crm",
            table: "customer_products",
            type: "character varying(255)",
            maxLength: 255,
            nullable: true);

        migrationBuilder.AddColumn<DateOnly>(
            name: "effective_date",
            schema: "crm",
            table: "customer_products",
            type: "date",
            nullable: true);

        migrationBuilder.AddColumn<DateOnly>(
            name: "expiry_date",
            schema: "crm",
            table: "customer_products",
            type: "date",
            nullable: true);

        migrationBuilder.AddColumn<decimal>(
            name: "fixed_discount",
            schema: "crm",
            table: "customer_products",
            type: "numeric(5,2)",
            precision: 5,
            scale: 2,
            nullable: true);

        migrationBuilder.AddColumn<decimal>(
            name: "fixed_price",
            schema: "crm",
            table: "customer_products",
            type: "numeric(10,2)",
            precision: 10,
            scale: 2,
            nullable: true);

        migrationBuilder.CreateTable(
            name: "customer_product_price_history",
            schema: "crm",
            columns: table => new
            {
                id = table.Column<Guid>(type: "uuid", nullable: false),
                customer_product_id = table.Column<Guid>(type: "uuid", nullable: false),
                fixed_price = table.Column<decimal>(type: "numeric(10,2)", precision: 10, scale: 2, nullable: true),
                fixed_discount = table.Column<decimal>(type: "numeric(5,2)", precision: 5, scale: 2, nullable: true),
                comments = table.Column<string>(type: "character varying(255)", maxLength: 255, nullable: true),
                effective_date = table.Column<DateOnly>(type: "date", nullable: true),
                expiry_date = table.Column<DateOnly>(type: "date", nullable: true),
                is_active = table.Column<bool>(type: "boolean", nullable: false),
                changed_at = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                changed_by = table.Column<Guid>(type: "uuid", nullable: false)
            },
            constraints: table =>
            {
                table.PrimaryKey("pk_customer_product_price_history", x => x.id);
                table.ForeignKey(
                    name: "fk_customer_product_price_history_customer_products_customer_p",
                    column: x => x.customer_product_id,
                    principalSchema: "crm",
                    principalTable: "customer_products",
                    principalColumn: "id",
                    onDelete: ReferentialAction.Cascade);
            });

        migrationBuilder.CreateIndex(
            name: "ix_customer_product_price_history_customer_product_id",
            schema: "crm",
            table: "customer_product_price_history",
            column: "customer_product_id");
    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropTable(
            name: "customer_product_price_history",
            schema: "crm");

        migrationBuilder.DropColumn(
            name: "comments",
            schema: "crm",
            table: "customer_products");

        migrationBuilder.DropColumn(
            name: "effective_date",
            schema: "crm",
            table: "customer_products");

        migrationBuilder.DropColumn(
            name: "expiry_date",
            schema: "crm",
            table: "customer_products");

        migrationBuilder.DropColumn(
            name: "fixed_discount",
            schema: "crm",
            table: "customer_products");

        migrationBuilder.DropColumn(
            name: "fixed_price",
            schema: "crm",
            table: "customer_products");

        migrationBuilder.CreateTable(
            name: "customer_product_prices",
            schema: "crm",
            columns: table => new
            {
                id = table.Column<Guid>(type: "uuid", nullable: false),
                comments = table.Column<string>(type: "character varying(255)", maxLength: 255, nullable: true),
                created_by = table.Column<Guid>(type: "uuid", nullable: false),
                created_on_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                customer_product_id = table.Column<Guid>(type: "uuid", nullable: false),
                deleted_by = table.Column<Guid>(type: "uuid", nullable: true),
                deleted_on_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: true),
                effective_date = table.Column<DateOnly>(type: "date", nullable: false),
                error_message = table.Column<string>(type: "text", nullable: true),
                expiry_date = table.Column<DateOnly>(type: "date", nullable: true),
                fixed_discount = table.Column<decimal>(type: "numeric(5,2)", precision: 5, scale: 2, nullable: true),
                fixed_price = table.Column<decimal>(type: "numeric(10,2)", precision: 10, scale: 2, nullable: true),
                is_active = table.Column<bool>(type: "boolean", nullable: false),
                is_deleted = table.Column<bool>(type: "boolean", nullable: false),
                last_modified_by = table.Column<Guid>(type: "uuid", nullable: true),
                last_modified_on_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: true),
                processed_on_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: true)
            },
            constraints: table =>
            {
                table.PrimaryKey("pk_customer_product_prices", x => x.id);
                table.ForeignKey(
                    name: "fk_customer_product_prices_customer_products_customer_product_",
                    column: x => x.customer_product_id,
                    principalSchema: "crm",
                    principalTable: "customer_products",
                    principalColumn: "id");
            });

        migrationBuilder.CreateIndex(
            name: "ix_customer_product_prices_customer_product_id",
            schema: "crm",
            table: "customer_product_prices",
            column: "customer_product_id");
    }
}
