// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Crowbond.Modules.CRM.Infrastructure.Database.Migrations;

/// <inheritdoc />
public partial class Add_Customer_Settings : Migration
{
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropColumn(
            name: "show_price_in_app",
            schema: "crm",
            table: "customers");

        migrationBuilder.DropColumn(
            name: "show_prices_in_delivery_docket",
            schema: "crm",
            table: "customers");

        migrationBuilder.CreateTable(
            name: "customer_settings",
            schema: "crm",
            columns: table => new
            {
                id = table.Column<Guid>(type: "uuid", nullable: false),
                customer_id = table.Column<Guid>(type: "uuid", nullable: false),
                show_prices_in_delivery_docket = table.Column<bool>(type: "boolean", nullable: false),
                show_price_in_app = table.Column<bool>(type: "boolean", nullable: false),
                show_logo_in_delivery_docket = table.Column<int>(type: "integer", nullable: false),
                customer_logo = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: true)
            },
            constraints: table =>
            {
                table.PrimaryKey("pk_customer_settings", x => x.id);
                table.ForeignKey(
                    name: "fk_customer_settings_customers_customer_id",
                    column: x => x.customer_id,
                    principalSchema: "crm",
                    principalTable: "customers",
                    principalColumn: "id",
                    onDelete: ReferentialAction.Cascade);
            });

        migrationBuilder.CreateIndex(
            name: "ix_customer_settings_customer_id",
            schema: "crm",
            table: "customer_settings",
            column: "customer_id",
            unique: true);
    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropTable(
            name: "customer_settings",
            schema: "crm");

        migrationBuilder.AddColumn<bool>(
            name: "show_price_in_app",
            schema: "crm",
            table: "customers",
            type: "boolean",
            nullable: false,
            defaultValue: false);

        migrationBuilder.AddColumn<bool>(
            name: "show_prices_in_delivery_docket",
            schema: "crm",
            table: "customers",
            type: "boolean",
            nullable: false,
            defaultValue: false);
    }
}
