// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Crowbond.Modules.CRM.Infrastructure.Database.Migrations;

/// <inheritdoc />
public partial class Add_CustomerProductPrice_Table : Migration
{
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropIndex(
            name: "ix_customer_products_customer_id",
            schema: "crm",
            table: "customer_products");

        migrationBuilder.DropColumn(
            name: "comments",
            schema: "crm",
            table: "customer_products");

        migrationBuilder.DropColumn(
            name: "created_by",
            schema: "crm",
            table: "customer_products");

        migrationBuilder.DropColumn(
            name: "created_on_utc",
            schema: "crm",
            table: "customer_products");

        migrationBuilder.DropColumn(
            name: "deleted_by",
            schema: "crm",
            table: "customer_products");

        migrationBuilder.DropColumn(
            name: "deleted_on_utc",
            schema: "crm",
            table: "customer_products");

        migrationBuilder.DropColumn(
            name: "effective_date",
            schema: "crm",
            table: "customer_products");

        migrationBuilder.DropColumn(
            name: "error_message",
            schema: "crm",
            table: "customer_products");

        migrationBuilder.DropColumn(
            name: "expiry_date",
            schema: "crm",
            table: "customer_products");

        migrationBuilder.DropColumn(
            name: "fixed_discount",
            schema: "crm",
            table: "customer_products");

        migrationBuilder.DropColumn(
            name: "fixed_price",
            schema: "crm",
            table: "customer_products");

        migrationBuilder.DropColumn(
            name: "is_deleted",
            schema: "crm",
            table: "customer_products");

        migrationBuilder.DropColumn(
            name: "last_modified_by",
            schema: "crm",
            table: "customer_products");

        migrationBuilder.DropColumn(
            name: "last_modified_on_utc",
            schema: "crm",
            table: "customer_products");

        migrationBuilder.DropColumn(
            name: "processed_on_utc",
            schema: "crm",
            table: "customer_products");

        migrationBuilder.CreateTable(
            name: "customer_product_prices",
            schema: "crm",
            columns: table => new
            {
                id = table.Column<Guid>(type: "uuid", nullable: false),
                customer_product_id = table.Column<Guid>(type: "uuid", nullable: false),
                fixed_price = table.Column<decimal>(type: "numeric(10,2)", precision: 10, scale: 2, nullable: true),
                fixed_discount = table.Column<decimal>(type: "numeric(5,2)", precision: 5, scale: 2, nullable: true),
                comments = table.Column<string>(type: "character varying(255)", maxLength: 255, nullable: true),
                effective_date = table.Column<DateOnly>(type: "date", nullable: false),
                expiry_date = table.Column<DateOnly>(type: "date", nullable: true),
                is_active = table.Column<bool>(type: "boolean", nullable: false),
                created_by = table.Column<Guid>(type: "uuid", nullable: false),
                created_on_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                last_modified_by = table.Column<Guid>(type: "uuid", nullable: true),
                last_modified_on_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: true),
                is_deleted = table.Column<bool>(type: "boolean", nullable: false),
                deleted_by = table.Column<Guid>(type: "uuid", nullable: true),
                deleted_on_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: true),
                processed_on_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: true),
                error_message = table.Column<string>(type: "text", nullable: true)
            },
            constraints: table =>
            {
                table.PrimaryKey("pk_customer_product_prices", x => x.id);
                table.ForeignKey(
                    name: "fk_customer_product_prices_customer_products_customer_product_",
                    column: x => x.customer_product_id,
                    principalSchema: "crm",
                    principalTable: "customer_products",
                    principalColumn: "id");
            });

        migrationBuilder.CreateIndex(
            name: "ix_customer_products_customer_id_product_id",
            schema: "crm",
            table: "customer_products",
            columns: new[] { "customer_id", "product_id" },
            unique: true);

        migrationBuilder.CreateIndex(
            name: "ix_customer_product_prices_customer_product_id",
            schema: "crm",
            table: "customer_product_prices",
            column: "customer_product_id");
    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropTable(
            name: "customer_product_prices",
            schema: "crm");

        migrationBuilder.DropIndex(
            name: "ix_customer_products_customer_id_product_id",
            schema: "crm",
            table: "customer_products");

        migrationBuilder.AddColumn<string>(
            name: "comments",
            schema: "crm",
            table: "customer_products",
            type: "character varying(255)",
            maxLength: 255,
            nullable: true);

        migrationBuilder.AddColumn<Guid>(
            name: "created_by",
            schema: "crm",
            table: "customer_products",
            type: "uuid",
            nullable: false,
            defaultValue: Guid.Empty);

        migrationBuilder.AddColumn<DateTime>(
            name: "created_on_utc",
            schema: "crm",
            table: "customer_products",
            type: "timestamp with time zone",
            nullable: false,
            defaultValue: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

        migrationBuilder.AddColumn<Guid>(
            name: "deleted_by",
            schema: "crm",
            table: "customer_products",
            type: "uuid",
            nullable: true);

        migrationBuilder.AddColumn<DateTime>(
            name: "deleted_on_utc",
            schema: "crm",
            table: "customer_products",
            type: "timestamp with time zone",
            nullable: true);

        migrationBuilder.AddColumn<DateOnly>(
            name: "effective_date",
            schema: "crm",
            table: "customer_products",
            type: "date",
            nullable: false,
            defaultValue: new DateOnly(1, 1, 1));

        migrationBuilder.AddColumn<string>(
            name: "error_message",
            schema: "crm",
            table: "customer_products",
            type: "text",
            nullable: true);

        migrationBuilder.AddColumn<DateOnly>(
            name: "expiry_date",
            schema: "crm",
            table: "customer_products",
            type: "date",
            nullable: true);

        migrationBuilder.AddColumn<decimal>(
            name: "fixed_discount",
            schema: "crm",
            table: "customer_products",
            type: "numeric(5,2)",
            precision: 5,
            scale: 2,
            nullable: true);

        migrationBuilder.AddColumn<decimal>(
            name: "fixed_price",
            schema: "crm",
            table: "customer_products",
            type: "numeric(10,2)",
            precision: 10,
            scale: 2,
            nullable: true);

        migrationBuilder.AddColumn<bool>(
            name: "is_deleted",
            schema: "crm",
            table: "customer_products",
            type: "boolean",
            nullable: false,
            defaultValue: false);

        migrationBuilder.AddColumn<Guid>(
            name: "last_modified_by",
            schema: "crm",
            table: "customer_products",
            type: "uuid",
            nullable: true);

        migrationBuilder.AddColumn<DateTime>(
            name: "last_modified_on_utc",
            schema: "crm",
            table: "customer_products",
            type: "timestamp with time zone",
            nullable: true);

        migrationBuilder.AddColumn<DateTime>(
            name: "processed_on_utc",
            schema: "crm",
            table: "customer_products",
            type: "timestamp with time zone",
            nullable: true);

        migrationBuilder.CreateIndex(
            name: "ix_customer_products_customer_id",
            schema: "crm",
            table: "customer_products",
            column: "customer_id");
    }
}
