// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Crowbond.Modules.CRM.Infrastructure.Database.Migrations;

/// <inheritdoc />
public partial class CustomerOutlet_Add_SoftDelete : Migration
{
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.RenameColumn(
            name: "last_modified_date",
            schema: "crm",
            table: "customer_outlets",
            newName: "last_modified_on_utc");

        migrationBuilder.RenameColumn(
            name: "create_date",
            schema: "crm",
            table: "customer_outlets",
            newName: "create_on_utc");

        migrationBuilder.AddColumn<DateTime>(
            name: "deleted_on_utc",
            schema: "crm",
            table: "customer_outlets",
            type: "timestamp with time zone",
            nullable: true);

        migrationBuilder.AddColumn<bool>(
            name: "is_deleted",
            schema: "crm",
            table: "customer_outlets",
            type: "boolean",
            nullable: false,
            defaultValue: false);
    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropColumn(
            name: "deleted_on_utc",
            schema: "crm",
            table: "customer_outlets");

        migrationBuilder.DropColumn(
            name: "is_deleted",
            schema: "crm",
            table: "customer_outlets");

        migrationBuilder.RenameColumn(
            name: "last_modified_on_utc",
            schema: "crm",
            table: "customer_outlets",
            newName: "last_modified_date");

        migrationBuilder.RenameColumn(
            name: "create_on_utc",
            schema: "crm",
            table: "customer_outlets",
            newName: "create_date");
    }
}
