// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Crowbond.Modules.CRM.Infrastructure.Database.Migrations;

/// <inheritdoc />
public partial class Alter_Audit_Culomns : Migration
{
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.RenameColumn(
            name: "last_modified_date",
            schema: "crm",
            table: "supplier_contacts",
            newName: "last_modified_on_utc");

        migrationBuilder.RenameColumn(
            name: "create_date",
            schema: "crm",
            table: "supplier_contacts",
            newName: "created_on_utc");

        migrationBuilder.RenameColumn(
            name: "create_by",
            schema: "crm",
            table: "supplier_contacts",
            newName: "created_by");

        migrationBuilder.RenameColumn(
            name: "last_modified_date",
            schema: "crm",
            table: "customers",
            newName: "last_modified_on_utc");

        migrationBuilder.RenameColumn(
            name: "create_date",
            schema: "crm",
            table: "customers",
            newName: "created_on_utc");

        migrationBuilder.RenameColumn(
            name: "create_by",
            schema: "crm",
            table: "customers",
            newName: "created_by");

        migrationBuilder.RenameColumn(
            name: "create_on_utc",
            schema: "crm",
            table: "customer_outlets",
            newName: "created_on_utc");

        migrationBuilder.RenameColumn(
            name: "create_by",
            schema: "crm",
            table: "customer_outlets",
            newName: "created_by");
    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.RenameColumn(
            name: "last_modified_on_utc",
            schema: "crm",
            table: "supplier_contacts",
            newName: "last_modified_date");

        migrationBuilder.RenameColumn(
            name: "created_on_utc",
            schema: "crm",
            table: "supplier_contacts",
            newName: "create_date");

        migrationBuilder.RenameColumn(
            name: "created_by",
            schema: "crm",
            table: "supplier_contacts",
            newName: "create_by");

        migrationBuilder.RenameColumn(
            name: "last_modified_on_utc",
            schema: "crm",
            table: "customers",
            newName: "last_modified_date");

        migrationBuilder.RenameColumn(
            name: "created_on_utc",
            schema: "crm",
            table: "customers",
            newName: "create_date");

        migrationBuilder.RenameColumn(
            name: "created_by",
            schema: "crm",
            table: "customers",
            newName: "create_by");

        migrationBuilder.RenameColumn(
            name: "created_on_utc",
            schema: "crm",
            table: "customer_outlets",
            newName: "create_on_utc");

        migrationBuilder.RenameColumn(
            name: "created_by",
            schema: "crm",
            table: "customer_outlets",
            newName: "create_by");
    }
}
