// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Crowbond.Modules.CRM.Infrastructure.Database.Migrations;

/// <inheritdoc />
public partial class Add_Table_Product_Categories : Migration
{
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropColumn(
            name: "brand_name",
            schema: "crm",
            table: "products");

        migrationBuilder.DropColumn(
            name: "category_name",
            schema: "crm",
            table: "products");

        migrationBuilder.DropColumn(
            name: "product_group_name",
            schema: "crm",
            table: "products");

        migrationBuilder.AlterColumn<string>(
            name: "name",
            schema: "crm",
            table: "products",
            type: "character varying(150)",
            maxLength: 150,
            nullable: false,
            oldClrType: typeof(string),
            oldType: "character varying(100)",
            oldMaxLength: 100);

        migrationBuilder.AddColumn<Guid>(
            name: "brand_id",
            schema: "crm",
            table: "products",
            type: "uuid",
            nullable: false,
            defaultValue: Guid.Empty);

        migrationBuilder.AddColumn<Guid>(
            name: "category_id",
            schema: "crm",
            table: "products",
            type: "uuid",
            nullable: false,
            defaultValue: Guid.Empty);

        migrationBuilder.AddColumn<Guid>(
            name: "product_group_id",
            schema: "crm",
            table: "products",
            type: "uuid",
            nullable: false,
            defaultValue: Guid.Empty);

        migrationBuilder.CreateTable(
            name: "brands",
            schema: "crm",
            columns: table => new
            {
                id = table.Column<Guid>(type: "uuid", nullable: false),
                name = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false)
            },
            constraints: table =>
            {
                table.PrimaryKey("pk_brands", x => x.id);
            });

        migrationBuilder.CreateTable(
            name: "categories",
            schema: "crm",
            columns: table => new
            {
                id = table.Column<Guid>(type: "uuid", nullable: false),
                name = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false)
            },
            constraints: table =>
            {
                table.PrimaryKey("pk_categories", x => x.id);
            });

        migrationBuilder.CreateTable(
            name: "product_groups",
            schema: "crm",
            columns: table => new
            {
                id = table.Column<Guid>(type: "uuid", nullable: false),
                name = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false)
            },
            constraints: table =>
            {
                table.PrimaryKey("pk_product_groups", x => x.id);
            });
    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropTable(
            name: "brands",
            schema: "crm");

        migrationBuilder.DropTable(
            name: "categories",
            schema: "crm");

        migrationBuilder.DropTable(
            name: "product_groups",
            schema: "crm");

        migrationBuilder.DropColumn(
            name: "brand_id",
            schema: "crm",
            table: "products");

        migrationBuilder.DropColumn(
            name: "category_id",
            schema: "crm",
            table: "products");

        migrationBuilder.DropColumn(
            name: "product_group_id",
            schema: "crm",
            table: "products");

        migrationBuilder.AlterColumn<string>(
            name: "name",
            schema: "crm",
            table: "products",
            type: "character varying(100)",
            maxLength: 100,
            nullable: false,
            oldClrType: typeof(string),
            oldType: "character varying(150)",
            oldMaxLength: 150);

        migrationBuilder.AddColumn<string>(
            name: "brand_name",
            schema: "crm",
            table: "products",
            type: "character varying(20)",
            maxLength: 20,
            nullable: false,
            defaultValue: "");

        migrationBuilder.AddColumn<string>(
            name: "category_name",
            schema: "crm",
            table: "products",
            type: "character varying(50)",
            maxLength: 50,
            nullable: false,
            defaultValue: "");

        migrationBuilder.AddColumn<string>(
            name: "product_group_name",
            schema: "crm",
            table: "products",
            type: "character varying(50)",
            maxLength: 50,
            nullable: false,
            defaultValue: "");
    }
}
