// <auto-generated />
using System;
using Crowbond.Modules.CRM.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Crowbond.Modules.CRM.Infrastructure.Database.Migrations
{
    [DbContext(typeof(CrmDbContext))]
    partial class CrmDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("crm")
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Crowbond.Modules.CRM.Domain.Customers.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccountNumber")
                        .HasColumnType("integer")
                        .HasColumnName("account_number");

                    b.Property<string>("BillingAddressLine1")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("billing_address_line1");

                    b.Property<string>("BillingAddressLine2")
                        .HasColumnType("text")
                        .HasColumnName("billing_address_line2");

                    b.Property<string>("BillingCountry")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("billing_country");

                    b.Property<string>("BillingCounty")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("billing_county");

                    b.Property<string>("BillingPostalCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("billing_postal_code");

                    b.Property<string>("BillingTownCity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("billing_town_city");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("company_name");

                    b.Property<string>("CustomerNotes")
                        .HasColumnType("text")
                        .HasColumnName("customer_notes");

                    b.Property<bool>("DetailedInvoice")
                        .HasColumnType("boolean")
                        .HasColumnName("detailed_invoice");

                    b.Property<string>("DriverCode")
                        .HasColumnType("text")
                        .HasColumnName("driver_code");

                    b.Property<Guid>("InvoicePeriodId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_period_id");

                    b.Property<int>("PaymentTerms")
                        .HasColumnType("integer")
                        .HasColumnName("payment_terms");

                    b.Property<int>("PriceGroupId")
                        .HasColumnType("integer")
                        .HasColumnName("price_group_id");

                    b.Property<string>("ShippingAddressLine1")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("shipping_address_line1");

                    b.Property<string>("ShippingAddressLine2")
                        .HasColumnType("text")
                        .HasColumnName("shipping_address_line2");

                    b.Property<string>("ShippingCountry")
                        .HasColumnType("text")
                        .HasColumnName("shipping_country");

                    b.Property<string>("ShippingCounty")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("shipping_county");

                    b.Property<string>("ShippingPostalCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("shipping_postal_code");

                    b.Property<string>("ShippingTownCity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("shipping_town_city");

                    b.HasKey("Id")
                        .HasName("pk_customers");

                    b.ToTable("customers", "crm");
                });
#pragma warning restore 612, 618
        }
    }
}
