namespace Crowbond.Modules.WMS.Application.Products.GetProductDetails;

public sealed record ProductDetailsResponse(
    Guid Id,
    string Sku,
    string Name,
    Guid? Parent,
    string FilterTypeName,
    string UnitOfMeasureName,
    Guid CategoryId,
    Guid BrandId,
    Guid ProductGroupId,
    string InventoryTypeName,
    int TaxRateType,
    int? Barcode,
    decimal? PackSize,
    string HandlingNotes,
    bool QiCheck,
    string Notes,
    decimal? ReorderLevel,
    decimal? Height,
    decimal? Width,
    decimal? Length,
    bool WeightInput,
    bool IsActive);
