namespace Crowbond.Modules.CRM.Application.Customers.GetCustomerOutlets;
public sealed record CustomerOutletResponse(
    Guid Id,
    Guid CustomerId,
    string LocationName,
    string FullName,
    string? Email,
    string PhoneNumber,
    string? Mobile,
    string AddressLine1,
    string? AddressLine2,
    string TownCity,
    string County,
    string? Country,
    string PostalCode,
    string? DeliveryNote,
    DateTime DeliveryTimeFrom,
    DateTime DeliveryTimeTo,
    bool Is24HrsDelivery);
