namespace Crowbond.Modules.CRM.Application.Customers.CreateCustomer;

public sealed record CustomerRequest(
    string BusinessName,
    string BillingAddressLine1,
    string? BillingAddressLine2,
    string BillingTownCity,
    string BillingCounty,
    string BillingCountry,
    string BillingPostalCode,
    Guid PriceTierId,
    decimal Discount,
    Guid? RepId,
    bool CustomPaymentTerm,
    int PaymentTerms,
    int? InvoiceDueDays,
    int DeliveryFeeSetting,
    decimal? DeliveryMinOrderValue,
    decimal? DeliveryCharge,
    bool NoDiscountSpecialItem,
    bool NoDiscountFixedPrice,
    bool DetailedInvoice,
    string? CustomerNotes,
    bool IsHq,
    bool ShowPricesInDeliveryDocket,
    bool ShowPriceInApp,
    int ShowLogoInDeliveryDocket);
