// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Crowbond.Modules.WMS.Infrastructure.Database.Migrations;

/// <inheritdoc />
public partial class Add_Dispatch_Tables : Migration
{
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.CreateTable(
            name: "dispatch_headers",
            schema: "wms",
            columns: table => new
            {
                id = table.Column<Guid>(type: "uuid", nullable: false),
                dispatch_no = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: false),
                order_id = table.Column<Guid>(type: "uuid", nullable: false),
                order_no = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: false),
                status = table.Column<int>(type: "integer", nullable: false),
                created_by = table.Column<Guid>(type: "uuid", nullable: false),
                created_on_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                last_modified_by = table.Column<Guid>(type: "uuid", nullable: true),
                last_modified_on_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: true)
            },
            constraints: table =>
            {
                table.PrimaryKey("pk_dispatch_headers", x => x.id);
            });

        migrationBuilder.CreateTable(
            name: "dispatch_lines",
            schema: "wms",
            columns: table => new
            {
                id = table.Column<Guid>(type: "uuid", nullable: false),
                dispatch_header_id = table.Column<Guid>(type: "uuid", nullable: false),
                product_id = table.Column<Guid>(type: "uuid", nullable: false),
                qty = table.Column<decimal>(type: "numeric(10,2)", precision: 10, scale: 2, nullable: false)
            },
            constraints: table =>
            {
                table.PrimaryKey("pk_dispatch_lines", x => x.id);
                table.ForeignKey(
                    name: "fk_dispatch_lines_dispatch_headers_dispatch_header_id",
                    column: x => x.dispatch_header_id,
                    principalSchema: "wms",
                    principalTable: "dispatch_headers",
                    principalColumn: "id",
                    onDelete: ReferentialAction.Cascade);
            });

        migrationBuilder.CreateIndex(
            name: "ix_dispatch_lines_dispatch_header_id",
            schema: "wms",
            table: "dispatch_lines",
            column: "dispatch_header_id");

        migrationBuilder.AddForeignKey(
            name: "fk_task_headers_dispatch_headers_entity_id",
            schema: "wms",
            table: "task_headers",
            column: "entity_id",
            principalSchema: "wms",
            principalTable: "dispatch_headers",
            principalColumn: "id",
            onDelete: ReferentialAction.Cascade);
    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropForeignKey(
            name: "fk_task_headers_dispatch_headers_entity_id",
            schema: "wms",
            table: "task_headers");

        migrationBuilder.DropTable(
            name: "dispatch_lines",
            schema: "wms");

        migrationBuilder.DropTable(
            name: "dispatch_headers",
            schema: "wms");
    }
}
