// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Crowbond.Modules.WMS.Infrastructure.Database.Migrations;

/// <inheritdoc />
public partial class Remove_Receipt_CreatedBy : Migration
{
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropColumn(
            name: "created_by",
            schema: "wms",
            table: "receipt_headers");

        migrationBuilder.DropColumn(
            name: "created_on_utc",
            schema: "wms",
            table: "receipt_headers");

        migrationBuilder.DropColumn(
            name: "created_by",
            schema: "wms",
            table: "dispatch_headers");

        migrationBuilder.DropColumn(
            name: "created_on_utc",
            schema: "wms",
            table: "dispatch_headers");

        migrationBuilder.AlterColumn<DateOnly>(
            name: "received_date",
            schema: "wms",
            table: "stocks",
            type: "date",
            nullable: false,
            oldClrType: typeof(DateTime),
            oldType: "timestamp with time zone");

        migrationBuilder.AlterColumn<DateOnly>(
            name: "received_date",
            schema: "wms",
            table: "receipt_headers",
            type: "date",
            nullable: true,
            oldClrType: typeof(DateTime),
            oldType: "timestamp with time zone");
    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.AlterColumn<DateTime>(
            name: "received_date",
            schema: "wms",
            table: "stocks",
            type: "timestamp with time zone",
            nullable: false,
            oldClrType: typeof(DateOnly),
            oldType: "date");

        migrationBuilder.AlterColumn<DateTime>(
            name: "received_date",
            schema: "wms",
            table: "receipt_headers",
            type: "timestamp with time zone",
            nullable: false,
            defaultValue: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
            oldClrType: typeof(DateOnly),
            oldType: "date",
            oldNullable: true);

        migrationBuilder.AddColumn<Guid>(
            name: "created_by",
            schema: "wms",
            table: "receipt_headers",
            type: "uuid",
            nullable: false,
            defaultValue: Guid.Empty);

        migrationBuilder.AddColumn<DateTime>(
            name: "created_on_utc",
            schema: "wms",
            table: "receipt_headers",
            type: "timestamp with time zone",
            nullable: false,
            defaultValue: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

        migrationBuilder.AddColumn<Guid>(
            name: "created_by",
            schema: "wms",
            table: "dispatch_headers",
            type: "uuid",
            nullable: false,
            defaultValue: Guid.Empty);

        migrationBuilder.AddColumn<DateTime>(
            name: "created_on_utc",
            schema: "wms",
            table: "dispatch_headers",
            type: "timestamp with time zone",
            nullable: false,
            defaultValue: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));
    }
}
