// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Crowbond.Modules.WMS.Infrastructure.Database.Migrations;

/// <inheritdoc />
public partial class Alter_FromLocation_Nullable : Migration
{
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropForeignKey(
            name: "fk_task_assignment_lines_locations_from_location_id",
            schema: "wms",
            table: "task_assignment_lines");

        migrationBuilder.AlterColumn<Guid>(
            name: "from_location_id",
            schema: "wms",
            table: "task_assignment_lines",
            type: "uuid",
            nullable: true,
            oldClrType: typeof(Guid),
            oldType: "uuid");

        migrationBuilder.AddForeignKey(
            name: "fk_task_assignment_lines_locations_from_location_id",
            schema: "wms",
            table: "task_assignment_lines",
            column: "from_location_id",
            principalSchema: "wms",
            principalTable: "locations",
            principalColumn: "id");
    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropForeignKey(
            name: "fk_task_assignment_lines_locations_from_location_id",
            schema: "wms",
            table: "task_assignment_lines");

        migrationBuilder.AlterColumn<Guid>(
            name: "from_location_id",
            schema: "wms",
            table: "task_assignment_lines",
            type: "uuid",
            nullable: false,
            defaultValue: Guid.Empty,
            oldClrType: typeof(Guid),
            oldType: "uuid",
            oldNullable: true);

        migrationBuilder.AddForeignKey(
            name: "fk_task_assignment_lines_locations_from_location_id",
            schema: "wms",
            table: "task_assignment_lines",
            column: "from_location_id",
            principalSchema: "wms",
            principalTable: "locations",
            principalColumn: "id",
            onDelete: ReferentialAction.Cascade);
    }
}
