// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Crowbond.Modules.WMS.Infrastructure.Database.Migrations;

/// <inheritdoc />
public partial class Remove_TaskHeader_EntityId : Migration
{
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropForeignKey(
            name: "fk_task_headers_dispatch_headers_entity_id",
            schema: "wms",
            table: "task_headers");

        migrationBuilder.DropForeignKey(
            name: "fk_task_headers_receipt_headers_entity_id",
            schema: "wms",
            table: "task_headers");

        migrationBuilder.DropIndex(
            name: "ix_task_headers_entity_id",
            schema: "wms",
            table: "task_headers");

        migrationBuilder.DropColumn(
            name: "entity_id",
            schema: "wms",
            table: "task_headers");

        migrationBuilder.AddColumn<Guid>(
            name: "dispatch_id",
            schema: "wms",
            table: "task_headers",
            type: "uuid",
            nullable: true);

        migrationBuilder.AddColumn<Guid>(
            name: "receipt_id",
            schema: "wms",
            table: "task_headers",
            type: "uuid",
            nullable: true);

        migrationBuilder.CreateIndex(
            name: "ix_task_headers_dispatch_id",
            schema: "wms",
            table: "task_headers",
            column: "dispatch_id");

        migrationBuilder.CreateIndex(
            name: "ix_task_headers_receipt_id",
            schema: "wms",
            table: "task_headers",
            column: "receipt_id");

        migrationBuilder.AddForeignKey(
            name: "fk_task_headers_dispatch_headers_dispatch_id",
            schema: "wms",
            table: "task_headers",
            column: "dispatch_id",
            principalSchema: "wms",
            principalTable: "dispatch_headers",
            principalColumn: "id");

        migrationBuilder.AddForeignKey(
            name: "fk_task_headers_receipt_headers_receipt_id",
            schema: "wms",
            table: "task_headers",
            column: "receipt_id",
            principalSchema: "wms",
            principalTable: "receipt_headers",
            principalColumn: "id");
    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropForeignKey(
            name: "fk_task_headers_dispatch_headers_dispatch_id",
            schema: "wms",
            table: "task_headers");

        migrationBuilder.DropForeignKey(
            name: "fk_task_headers_receipt_headers_receipt_id",
            schema: "wms",
            table: "task_headers");

        migrationBuilder.DropIndex(
            name: "ix_task_headers_dispatch_id",
            schema: "wms",
            table: "task_headers");

        migrationBuilder.DropIndex(
            name: "ix_task_headers_receipt_id",
            schema: "wms",
            table: "task_headers");

        migrationBuilder.DropColumn(
            name: "dispatch_id",
            schema: "wms",
            table: "task_headers");

        migrationBuilder.DropColumn(
            name: "receipt_id",
            schema: "wms",
            table: "task_headers");

        migrationBuilder.AddColumn<Guid>(
            name: "entity_id",
            schema: "wms",
            table: "task_headers",
            type: "uuid",
            nullable: false,
            defaultValue: new Guid("00000000-0000-0000-0000-000000000000"));

        migrationBuilder.CreateIndex(
            name: "ix_task_headers_entity_id",
            schema: "wms",
            table: "task_headers",
            column: "entity_id");

        migrationBuilder.AddForeignKey(
            name: "fk_task_headers_dispatch_headers_entity_id",
            schema: "wms",
            table: "task_headers",
            column: "entity_id",
            principalSchema: "wms",
            principalTable: "dispatch_headers",
            principalColumn: "id",
            onDelete: ReferentialAction.Cascade);

        migrationBuilder.AddForeignKey(
            name: "fk_task_headers_receipt_headers_entity_id",
            schema: "wms",
            table: "task_headers",
            column: "entity_id",
            principalSchema: "wms",
            principalTable: "receipt_headers",
            principalColumn: "id",
            onDelete: ReferentialAction.Cascade);
    }
}
