// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Crowbond.Modules.WMS.Infrastructure.Database.Migrations;

/// <inheritdoc />
public partial class Products_Add_TaxRateType : Migration
{
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.RenameColumn(
            name: "active",
            schema: "wms",
            table: "products",
            newName: "is_active");

        migrationBuilder.AddColumn<int>(
            name: "tax_rate_type",
            schema: "wms",
            table: "products",
            type: "integer",
            nullable: false,
            defaultValue: 0);
    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropColumn(
            name: "tax_rate_type",
            schema: "wms",
            table: "products");

        migrationBuilder.RenameColumn(
            name: "is_active",
            schema: "wms",
            table: "products",
            newName: "active");
    }
}
