// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Crowbond.Modules.WMS.Infrastructure.Database.Migrations;

/// <inheritdoc />
public partial class Add_Id_To_Product_Categories : Migration
{
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropForeignKey(
            name: "fk_products_brands_brand_name",
            schema: "wms",
            table: "products");

        migrationBuilder.DropForeignKey(
            name: "fk_products_categories_category_name",
            schema: "wms",
            table: "products");

        migrationBuilder.DropForeignKey(
            name: "fk_products_product_groups_product_group_name",
            schema: "wms",
            table: "products");

        migrationBuilder.DropIndex(
            name: "ix_products_brand_name",
            schema: "wms",
            table: "products");

        migrationBuilder.DropIndex(
            name: "ix_products_category_name",
            schema: "wms",
            table: "products");

        migrationBuilder.DropIndex(
            name: "ix_products_product_group_name",
            schema: "wms",
            table: "products");

        migrationBuilder.DropPrimaryKey(
            name: "pk_product_groups",
            schema: "wms",
            table: "product_groups");

        migrationBuilder.DropPrimaryKey(
            name: "pk_categories",
            schema: "wms",
            table: "categories");

        migrationBuilder.DropPrimaryKey(
            name: "pk_brands",
            schema: "wms",
            table: "brands");

        migrationBuilder.DropColumn(
            name: "brand_name",
            schema: "wms",
            table: "products");

        migrationBuilder.DropColumn(
            name: "category_name",
            schema: "wms",
            table: "products");

        migrationBuilder.DropColumn(
            name: "product_group_name",
            schema: "wms",
            table: "products");

        migrationBuilder.AlterColumn<string>(
            name: "name",
            schema: "wms",
            table: "products",
            type: "character varying(150)",
            maxLength: 150,
            nullable: false,
            oldClrType: typeof(string),
            oldType: "character varying(100)",
            oldMaxLength: 100);

        migrationBuilder.AddColumn<Guid>(
            name: "brand_id",
            schema: "wms",
            table: "products",
            type: "uuid",
            nullable: false,
            defaultValue: Guid.Empty);

        migrationBuilder.AddColumn<Guid>(
            name: "category_id",
            schema: "wms",
            table: "products",
            type: "uuid",
            nullable: false,
            defaultValue: Guid.Empty);

        migrationBuilder.AddColumn<Guid>(
            name: "product_group_id",
            schema: "wms",
            table: "products",
            type: "uuid",
            nullable: false,
            defaultValue: Guid.Empty);

        migrationBuilder.AlterColumn<string>(
            name: "name",
            schema: "wms",
            table: "product_groups",
            type: "character varying(100)",
            maxLength: 100,
            nullable: false,
            oldClrType: typeof(string),
            oldType: "character varying(50)",
            oldMaxLength: 50);

        migrationBuilder.AddColumn<Guid>(
            name: "id",
            schema: "wms",
            table: "product_groups",
            type: "uuid",
            nullable: false,
            defaultValue: Guid.Empty);

        migrationBuilder.AlterColumn<string>(
            name: "name",
            schema: "wms",
            table: "categories",
            type: "character varying(100)",
            maxLength: 100,
            nullable: false,
            oldClrType: typeof(string),
            oldType: "character varying(50)",
            oldMaxLength: 50);

        migrationBuilder.AddColumn<Guid>(
            name: "id",
            schema: "wms",
            table: "categories",
            type: "uuid",
            nullable: false,
            defaultValue: Guid.Empty);

        migrationBuilder.AlterColumn<string>(
            name: "name",
            schema: "wms",
            table: "brands",
            type: "character varying(100)",
            maxLength: 100,
            nullable: false,
            oldClrType: typeof(string),
            oldType: "character varying(20)",
            oldMaxLength: 20);

        migrationBuilder.AddColumn<Guid>(
            name: "id",
            schema: "wms",
            table: "brands",
            type: "uuid",
            nullable: false,
            defaultValue: Guid.Empty);

        migrationBuilder.AddPrimaryKey(
            name: "pk_product_groups",
            schema: "wms",
            table: "product_groups",
            column: "id");

        migrationBuilder.AddPrimaryKey(
            name: "pk_categories",
            schema: "wms",
            table: "categories",
            column: "id");

        migrationBuilder.AddPrimaryKey(
            name: "pk_brands",
            schema: "wms",
            table: "brands",
            column: "id");

        migrationBuilder.CreateIndex(
            name: "ix_products_brand_id",
            schema: "wms",
            table: "products",
            column: "brand_id");

        migrationBuilder.CreateIndex(
            name: "ix_products_category_id",
            schema: "wms",
            table: "products",
            column: "category_id");

        migrationBuilder.CreateIndex(
            name: "ix_products_product_group_id",
            schema: "wms",
            table: "products",
            column: "product_group_id");

        migrationBuilder.AddForeignKey(
            name: "fk_products_brands_brand_id",
            schema: "wms",
            table: "products",
            column: "brand_id",
            principalSchema: "wms",
            principalTable: "brands",
            principalColumn: "id");

        migrationBuilder.AddForeignKey(
            name: "fk_products_categories_category_id",
            schema: "wms",
            table: "products",
            column: "category_id",
            principalSchema: "wms",
            principalTable: "categories",
            principalColumn: "id");

        migrationBuilder.AddForeignKey(
            name: "fk_products_product_groups_product_group_id",
            schema: "wms",
            table: "products",
            column: "product_group_id",
            principalSchema: "wms",
            principalTable: "product_groups",
            principalColumn: "id");
    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropForeignKey(
            name: "fk_products_brands_brand_id",
            schema: "wms",
            table: "products");

        migrationBuilder.DropForeignKey(
            name: "fk_products_categories_category_id",
            schema: "wms",
            table: "products");

        migrationBuilder.DropForeignKey(
            name: "fk_products_product_groups_product_group_id",
            schema: "wms",
            table: "products");

        migrationBuilder.DropIndex(
            name: "ix_products_brand_id",
            schema: "wms",
            table: "products");

        migrationBuilder.DropIndex(
            name: "ix_products_category_id",
            schema: "wms",
            table: "products");

        migrationBuilder.DropIndex(
            name: "ix_products_product_group_id",
            schema: "wms",
            table: "products");

        migrationBuilder.DropPrimaryKey(
            name: "pk_product_groups",
            schema: "wms",
            table: "product_groups");

        migrationBuilder.DropPrimaryKey(
            name: "pk_categories",
            schema: "wms",
            table: "categories");

        migrationBuilder.DropPrimaryKey(
            name: "pk_brands",
            schema: "wms",
            table: "brands");

        migrationBuilder.DropColumn(
            name: "brand_id",
            schema: "wms",
            table: "products");

        migrationBuilder.DropColumn(
            name: "category_id",
            schema: "wms",
            table: "products");

        migrationBuilder.DropColumn(
            name: "product_group_id",
            schema: "wms",
            table: "products");

        migrationBuilder.DropColumn(
            name: "id",
            schema: "wms",
            table: "product_groups");

        migrationBuilder.DropColumn(
            name: "id",
            schema: "wms",
            table: "categories");

        migrationBuilder.DropColumn(
            name: "id",
            schema: "wms",
            table: "brands");

        migrationBuilder.AlterColumn<string>(
            name: "name",
            schema: "wms",
            table: "products",
            type: "character varying(100)",
            maxLength: 100,
            nullable: false,
            oldClrType: typeof(string),
            oldType: "character varying(150)",
            oldMaxLength: 150);

        migrationBuilder.AddColumn<string>(
            name: "brand_name",
            schema: "wms",
            table: "products",
            type: "character varying(20)",
            maxLength: 20,
            nullable: false,
            defaultValue: "");

        migrationBuilder.AddColumn<string>(
            name: "category_name",
            schema: "wms",
            table: "products",
            type: "character varying(50)",
            maxLength: 50,
            nullable: false,
            defaultValue: "");

        migrationBuilder.AddColumn<string>(
            name: "product_group_name",
            schema: "wms",
            table: "products",
            type: "character varying(50)",
            maxLength: 50,
            nullable: false,
            defaultValue: "");

        migrationBuilder.AlterColumn<string>(
            name: "name",
            schema: "wms",
            table: "product_groups",
            type: "character varying(50)",
            maxLength: 50,
            nullable: false,
            oldClrType: typeof(string),
            oldType: "character varying(100)",
            oldMaxLength: 100);

        migrationBuilder.AlterColumn<string>(
            name: "name",
            schema: "wms",
            table: "categories",
            type: "character varying(50)",
            maxLength: 50,
            nullable: false,
            oldClrType: typeof(string),
            oldType: "character varying(100)",
            oldMaxLength: 100);

        migrationBuilder.AlterColumn<string>(
            name: "name",
            schema: "wms",
            table: "brands",
            type: "character varying(20)",
            maxLength: 20,
            nullable: false,
            oldClrType: typeof(string),
            oldType: "character varying(100)",
            oldMaxLength: 100);

        migrationBuilder.AddPrimaryKey(
            name: "pk_product_groups",
            schema: "wms",
            table: "product_groups",
            column: "name");

        migrationBuilder.AddPrimaryKey(
            name: "pk_categories",
            schema: "wms",
            table: "categories",
            column: "name");

        migrationBuilder.AddPrimaryKey(
            name: "pk_brands",
            schema: "wms",
            table: "brands",
            column: "name");

        migrationBuilder.CreateIndex(
            name: "ix_products_brand_name",
            schema: "wms",
            table: "products",
            column: "brand_name");

        migrationBuilder.CreateIndex(
            name: "ix_products_category_name",
            schema: "wms",
            table: "products",
            column: "category_name");

        migrationBuilder.CreateIndex(
            name: "ix_products_product_group_name",
            schema: "wms",
            table: "products",
            column: "product_group_name");

        migrationBuilder.AddForeignKey(
            name: "fk_products_brands_brand_name",
            schema: "wms",
            table: "products",
            column: "brand_name",
            principalSchema: "wms",
            principalTable: "brands",
            principalColumn: "name");

        migrationBuilder.AddForeignKey(
            name: "fk_products_categories_category_name",
            schema: "wms",
            table: "products",
            column: "category_name",
            principalSchema: "wms",
            principalTable: "categories",
            principalColumn: "name");

        migrationBuilder.AddForeignKey(
            name: "fk_products_product_groups_product_group_name",
            schema: "wms",
            table: "products",
            column: "product_group_name",
            principalSchema: "wms",
            principalTable: "product_groups",
            principalColumn: "name");
    }
}
